import GetNFTS from "@/components/get-nfts";
import Header from "@/components/Header";
import styles from "@/styles/home.module.css";
import Head from "next/head";
const Moralis = require("moralis").default;

Moralis.start({
  apiKey: process.env.MORALIS_API_KEY,
});

export default function Home() {
  // return (
  // <div className="p-9 flex justify-between">
  //   <div>
  //     <h1 className="text-3xl">MintMate</h1>
  //   </div>
  //   <div className="flex">
  //     {address ? (
  //       <div className="mr-8">
  //         <button className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg">
  //           Mint
  //         </button>
  //       </div>
  //     ) : (
  //       <div></div>
  //     )}
  //     <ConnectWallet />
  //   </div>
  // </div>
  // );

  console.log("indexxxx");
  return (
    <section className={styles.container}>
      <Head>
        <title>MintMate: NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <section className={styles.main}>
          <Header />
          <GetNFTS />
          {/* <HeroSection /> */}
          {/* <AirdropPopUp /> */}
        </section>
        {/* <TrendingSection /> */}
      </section>
    </section>
  );
}
